[package]
name = "testutil"
version = "0.0.0"
description = "Helper crate for Isahc tests."
edition = "2018"
publish = false

[dependencies]
crossbeam-channel = "0.4"
ctor = "0.1"
env_logger = "0.7"
lazy_static = "1"
tiny_http = "0.7"
tracing-subscriber = "0.2"
