name: configure repo
on:
  push:
    branches: [master]

jobs:
  configure-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: micnncim/action-label-syncer@v1
